import {
  emptyAllCrashVehiclesValues,
  emptyAllThirdPartyInjuredValues,
  emptyCrashVehicleValues,
  emptyDamageElectronicValues,
  emptyDamageVehiclesValues,
  emptyElectronicValues,
  emptyFireVehiclesValues,
  emptyGncValues,
  emptyIsTireValues,
  emptyPhoneValues,
  emptyTheftElectronicValues,
  emptyTheftVehiclesValues,
  emptyVehicleReportValues,
  touchedAllCrashVehiclesValues,
  touchedAllCrashVehiclesValuesTrue,
  touchedAllThirdPartyInjuredValues,
  touchedAllThirdPartyInjuredValuesTrue,
  touchedCrashVehicleValues,
  touchedCrashVehicleValuesTrue,
  touchedDamageElectronicValues,
  touchedDamageElectronicValuesTrue,
  touchedDamageVehiclesValues,
  touchedDamageVehiclesValuesTrue,
  touchedElectronicValues,
  touchedElectronicValuesTrue,
  touchedFireVehiclesValues,
  touchedFireVehiclesValuesTrue,
  touchedGncValues,
  touchedGncValuesTrue,
  touchedIsTireValues,
  touchedIsTireValuesTrue,
  touchedPhoneValues,
  touchedPhoneValuesTrue,
  touchedTheftElectronicValues,
  touchedTheftElectronicValuesTrue,
  touchedTheftVehiclesValues,
  touchedTheftVehiclesValuesTrue,
  touchedVehicleReportValues,
  touchedVehicleReportValuesTrue
} from "@/utilities";
import { ClientCreateReportValues, TouchedClientCreateReportValues } from "../..";

export const emptyClientCreateReportValues: ClientCreateReportValues = {
  vehicleReport: emptyVehicleReportValues,
  electronic: emptyElectronicValues,
  gnc: emptyGncValues,
  phone: emptyPhoneValues,
  theftVehicle: emptyTheftVehiclesValues,
  theftElectronic: emptyTheftElectronicValues,
  damageVehicle: emptyDamageVehiclesValues,
  damageElectronic: emptyDamageElectronicValues,
  isTire: emptyIsTireValues,
  fire: emptyFireVehiclesValues,
  crash: emptyCrashVehicleValues,
  thirdPartyInjured: emptyAllThirdPartyInjuredValues,
  thirdPartyVehicle: emptyAllCrashVehiclesValues,
  swornDeclaration: { swornDeclaration: false },
};

export const touchedClientCreateReportValues: TouchedClientCreateReportValues = {
  vehicleReport: touchedVehicleReportValues,
  electronic: touchedElectronicValues,
  gnc: touchedGncValues,
  phone: touchedPhoneValues,
  theftVehicle: touchedTheftVehiclesValues,
  theftElectronic: touchedTheftElectronicValues,
  damageVehicle: touchedDamageVehiclesValues,
  damageElectronic: touchedDamageElectronicValues,
  isTire: touchedIsTireValues,
  fire: touchedFireVehiclesValues,
  crash: touchedCrashVehicleValues,
  thirdPartyInjured: touchedAllThirdPartyInjuredValues,
  thirdPartyVehicle: touchedAllCrashVehiclesValues,
  swornDeclaration: { swornDeclaration: false },
};

export const touchedClientCreateReportValuesTrue: TouchedClientCreateReportValues = {
  vehicleReport: touchedVehicleReportValuesTrue,
  electronic: touchedElectronicValuesTrue,
  gnc: touchedGncValuesTrue,
  phone: touchedPhoneValuesTrue,
  theftVehicle: touchedTheftVehiclesValuesTrue,
  theftElectronic: touchedTheftElectronicValuesTrue,
  damageVehicle: touchedDamageVehiclesValuesTrue,
  damageElectronic: touchedDamageElectronicValuesTrue,
  isTire: touchedIsTireValuesTrue,
  fire: touchedFireVehiclesValuesTrue,
  crash: touchedCrashVehicleValuesTrue,
  thirdPartyInjured: touchedAllThirdPartyInjuredValuesTrue,
  thirdPartyVehicle: touchedAllCrashVehiclesValuesTrue,
  swornDeclaration: { swornDeclaration: true },
};
