export enum PublicRoutes {
  PUBLIC = "public",
  HOME = "home",
  LOGIN = "login",
  INSPECT = "inspeccionar",
  REPORT = "denunciar",
  REGISTER = "registrarse",
  FORGOTTEM_PASSWORD = "contraseña",
  CREATE_INSPECTION = "crear-inspeccion",
  CREATE_SINISTER = "crear-siniestro",
  VERIFIED = 'verificado',
  NOT_VERIFIED = 'no-verificado',
  ABOUT_US = 'sobre-nosotros',
  FREQUENT_QUESTIONS = 'preguntas-frecuentes'
}

export enum PrivateRoutes {
  PRIVATE = "private",
  BROKER = "broker",
  ADMIN = "admin",
  CLIENT = "cliente",
  DASHBOARD = "dashboard",
  ELEMENTS = "elementos",
  CREATE_INSPECTION_MANUAL = "crear-inspeccion-manual",
  CREATE_INSPECTION = "crear-inspeccion",
  CREATE_SINISTER = "crear-siniestro",
  CREATE_SINISTER_MANUAL = "crear-siniestro-manual",
  CREATE_SINISTER_IN_INSURED = "crear-siniestro-en",
  ALL_INSURED = "asegurados",
  ALL_SINISTER = "siniestros",
  INSURED_DETAIL = "asegurados",
  SINISTER_DETAIL = "siniestros",
  MY_PROFILE = "perfil",
  CLIENTS_OF_BROKER = "clientes",
  USERS_OF_ADMIN = "usuarios",
  SEARCH_CLIENT = "buscar-cliente",
  SEARCH_USER = "buscar-usuario",
  INSPECTIONS = "inspecciones",
}
