export type TouchedForms =
  | "personal"
  | "legalPersonal"
  | "registerPersonal"
  | "registerLegalPersonal"
  | "registerBrokerPersonal"
  | "registerBrokerLegalPersonal"
  | "vehicle"
  | "electronic"
  | "vehicleReport"
  | "theftVehicle"
  | "theftElectronic"
  | "fire"
  | "crash"
  | "thirdPartyInjured"
  | "thirdPartyVehicle"
  | "";
