export type TouchedForms =
  | "personal"
  | "legalPersonal"
  | "brokerPersonal"
  | "brokerLegalPersonal"
  | "vehicle"
  | "electronic"
  | "vehicleReport"
  | "theftVehicle"
  | "theftElectronic"
  | "fire"
  | "crash"
  | "thirdPartyInjured"
  | "thirdPartyVehicle"
  | "";
