import { ThirdPartyVehicleValues, TouchedThirdPartyVehicleValues } from "../../models";

export const emptyThirdPartyVehicleValues: ThirdPartyVehicleValues = {
  year: 0,
  brand: "",
  model: "",
  plate: "",
  insuranceCompany: "",
  insurancePolicy: "",
  ownerName: "",
  ownerLastName: "",
  ownerDni: "",
  address: "",
  phoneNumber: "",
  licensePhoto: [],
  email: "",
  owner: true,
  name: "",
  lastName: "",
  dni: "",
};

export const touchedThirdPartyVehicleValues: TouchedThirdPartyVehicleValues = {
  year: false,
  brand: false,
  model: false,
  plate: false,
  insuranceCompany: false,
  insurancePolicy: false,
  ownerName: false,
  ownerLastName: false,
  ownerDni: false,
  address: false,
  phoneNumber: false,
  licensePhoto: false,
  email: false,
  name: false,
  lastName: false,
  dni: false,
};

export const touchedThirdPartyVehicleValuesTrue: TouchedThirdPartyVehicleValues = {
  year: true,
  brand: true,
  model: true,
  plate: true,
  insuranceCompany: true,
  insurancePolicy: true,
  ownerName: true,
  ownerLastName: true,
  ownerDni: true,
  address: true,
  phoneNumber: true,
  licensePhoto: true,
  email: true,
  name: true,
  lastName: true,
  dni: true,
};
